## Issue Welcome Comments ##

# Comment to send on a user's first issue in the repository.
firstIssueWelcomeComment: |
  Congratulations on opening your first issue in this repository. A maintainer will get by as soon as possible to address this issue.
  
  Cheers,
  Bastion

# Comment to send on the user's forthcoming issues in the repository.
issueWelcomeComment: |
  Thank you for opening this issue. A maintainer will get by as soon as possible to address this issue.
  
  Cheers,
  Bastion


## Pull Request Welcome Comments ##

# Comment to send on a user's first pull request in the repository.
firstPullRequestWelcomeComment: |
  Congratulations on opening your first pull request in this repository. A maintainer will get by as soon as possible to review the changes.
  
  Cheers,
  Bastion

# Comment to send on the user's forthcoming pull requests in the repository.
pullRequestWelcomeComment: |
  Thank you for opening this pull request. A maintainer will get by as soon as possible to review the changes.
  
  Cheers,
  Bastion
